services:
  mediadriver:
    build: ./MediaDriver
    container_name: mediadriver
    shm_size: '1024m'
    ipc: shareable
    ports:
      - 40456:40456/udp
  publisher1:
    build:
      context: .
      dockerfile: ./Publisher/Dockerfile
    ipc: container:mediadriver
    depends_on:
      - mediadriver
    command: --period=00:00:00.5 --channel=aeron:udp?endpoint=224.0.1.1:40456
  subscriber1:
    build:
      context: .
      dockerfile: ./Subscriber/Dockerfile
    ipc: container:mediadriver
    depends_on:
      - mediadriver
    command:  --channel=aeron:udp?endpoint=224.0.1.1:40456
  subscriber2:
    build:
      context: .
      dockerfile: ./Subscriber/Dockerfile
    ipc: container:mediadriver
    depends_on:
      - mediadriver
    command:  --channel=aeron:udp?endpoint=224.0.1.1:40456